- name: Ansible Playbook to restore backups for GitLab Community Edition "gitlab-ce={{ gitlab_version }}"
  hosts: "{{ host }}" 
  become: yes
  become_user: root
  vars_files:
    - env_vars.yml
  
  tasks:
  - name: restoring backups for gitlab using script
    shell: |
      sudo cp "{{ backup_file_tar }}" /var/opt/gitlab/backups/
      sudo chown git.git /var/opt/gitlab/backups/*gitlab_backup.tar
      sudo chown gitlab-redis /var/opt/gitlab/redis
      sudo chown gitlab-redis:gitlab-redis /var/opt/gitlab/redis/dump.rdb
      sudo chown git:root /var/opt/gitlab/backups
      sudo chown git:git /var/opt/gitlab/backups/*gitlab_backup.tar
      sudo gitlab-ctl stop puma
      sudo gitlab-ctl stop sidekiq
      sudo gitlab-ctl stop unicorn
      sudo gitlab-ctl status
      sudo gitlab-backup restore BACKUP="{{ backup_value }}" --trace
      sudo gitlab-ctl restart

    # sudo gitlab-rake gitlab:backup:restore BACKUP = "{{ backup_value }}"
    # sudo gitlab-backup restore BACKUP="{{ backup_value }}" --trace

# # This procedure assumes that:

# #     You have installed the exact same version and type (CE/EE) of GitLab Omnibus with which the backup was created.
# #     You have run sudo gitlab-ctl reconfigure at least once.
# #     GitLab is running. If not, start it using sudo gitlab-ctl start. 

# #First ensure your backup tar file is in the backup directory described in the gitlab.rb configuration gitlab_rails['backup_path']. The default is /var/opt/gitlab/backups. It needs to be owned by the git user.

# sudo cp "{{ backup_file_tar }}" /var/opt/gitlab/backups/
# sudo chown git.git /var/opt/gitlab/backups/*gitlab_backup.tar
# sudo chown gitlab-redis /var/opt/gitlab/redis
# sudo chown gitlab-redis:gitlab-redis /var/opt/gitlab/redis/dump.rdb
# sudo chown git:root /var/opt/gitlab/backups
# sudo chown git:git /var/opt/gitlab/backups/*gitlab_backup.tar

# #This command will Stop the processes that are connected to the database. we'll Leave the rest of GitLab running: 
# sudo gitlab-ctl stop puma
# sudo gitlab-ctl stop sidekiq
# # Verify
# sudo gitlab-ctl status
# # This command will overwrite the contents of your GitLab database!
# sudo gitlab-backup restore BACKUP="{{ backup_value }}" --trace

