- name: Ansible Playbook to restore backups for GitLab Community Edition "gitlab-ce={{ gitlab_version }}"
  hosts: "{{ host }}" 
  become: yes
  become_user: root
  vars_files:
    - env_vars.yml
  
  tasks:
  - name: restoring backups for gitlab using script
    shell: |
      sudo gitlab-ctl stop unicorn
      sudo gitlab-ctl stop sidekiq
      sudo gitlab-ctl status
      sudo gitlab-rake gitlab:backup:restore BACKUP = "{{ backup_value }}"
      sudo gitlab-ctl restart

  # tasks:
  # - name: restoring backups for gitlab using script
  #   shell: |
  #     sudo gitlab-ctl stop unicorn
  #     sudo gitlab-ctl stop sidekiq
  #     sudo cp <backup file> /var/opt/gitlab/backups/
  #     sudo gitlab-backup restore BACKUP=<backup file name>
  #     sudo cp /var/opt/gitlab/backups/<backup file name>.tar /etc/gitlab/
  #     sudo gitlab-ctl reconfigure
  #     sudo cp /var/opt/gitlab/backups/<backup file name>.tar /var/opt/gitlab/gitlab-rails/uploads/
  #     sudo gitlab-ctl restart
  #     sudo gitlab-ctl tail